#________________________________
# pick an object
# It is a service to pick an object on pytamp and get planned joint_path.
#________________________________

float32[6] current_joint
string object_name 
---
float32[] pre_grasp
float32[] grasp
float32[] post_grasp

